
testing: true 

# Site Settings
# Course Info
title: "Applied Algebra"
email: daniel.krashen@rutgers.edu
tagline: "Rutgers MATH 428 Spring 2020"
description: "Applied Algebra"
instructor: "Danny Krashen"
instructor_email: "&#x64;&#x61;&#x6e;&#x69;&#x65;&#x6c;&period;&#x6b;&#x72;&#x61;&#x73;&#x68;&#x65;&#x6e;&plus;&#x61;&#x70;&#x70;&#x61;&#x6c;&#x67;&commat;&#x67;&#x6d;&#x61;&#x69;&#x6c;&period;&#x63;&#x6f;&#x6d;"
office: "Hill 220"
office-hour: "Wed 11-12/ Mon 2:30-3:30 (tentative)"
lecture-schedule: "Monday/Thursday 12:00pm -- 1:20pm<br />Allison Road Classroom, Room 205"
instructor_url: "http://dkrashen.org"



baseurl: "/appliedalgebra"
